import React from "react";
import { useSteveStore } from "../../../stores/steveStore";

export default function SummaryCard({ snapshot, messageId }) {
  const openEdit = useSteveStore((s) => s.openEditModal);
  const saveDraft = useSteveStore((s) => s.saveDraft);
  const createCampaign = useSteveStore((s) => s.createCampaign);

  const s = snapshot || {};
  const metrics = s.metrics || {};

  const handleSaveDraft = async () => {
    await saveDraft(snapshot);
    alert("Draft saved successfully!");
  };

  return (
    <div style={{
      background: "#FFFFFF",
      borderRadius: 16,
      padding: 20,
      marginTop: 10,
      boxShadow: "0 6px 24px rgba(15,23,42,0.04)",
      border: "1px solid #E8EDF5",
      maxWidth: 900,
      marginBottom: 16
    }}>
      <div style={{ display: "flex", gap: 16, flexWrap: "wrap" }}>
        <div style={{ flex: 2, minWidth: 300 }}>
          <div style={{ fontWeight: 700, fontSize: 18, color: "#0F172A" }}>
            {s.title || "Campaign Overview"}
          </div>
          <div style={{ color: "#64748B", marginTop: 6, fontSize: 14, lineHeight: "20px" }}>
            {s.summary || "Summary generated by Steve AI."}
          </div>

          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12, marginTop: 16 }}>
            <div>
              <div style={{ fontSize: 12, fontWeight: 600, color: "#94A3B8", marginBottom: 4 }}>Objective</div>
              <div style={{ color: "#0F172A", fontSize: 14 }}>{s.objective || "—"}</div>
            </div>
            <div>
              <div style={{ fontSize: 12, fontWeight: 600, color: "#94A3B8", marginBottom: 4 }}>Location</div>
              <div style={{ color: "#0F172A", fontSize: 14 }}>{s.location || "—"}</div>
            </div>
            <div>
              <div style={{ fontSize: 12, fontWeight: 600, color: "#94A3B8", marginBottom: 4 }}>Budget</div>
              <div style={{ color: "#0F172A", fontSize: 14 }}>{s.budget || "—"}</div>
            </div>
            <div>
              <div style={{ fontSize: 12, fontWeight: 600, color: "#94A3B8", marginBottom: 4 }}>Audience</div>
              <div style={{ color: "#0F172A", fontSize: 14 }}>{s.audience || "—"}</div>
            </div>
          </div>
        </div>

        <div style={{ flex: 1, minWidth: 240 }}>
          <div style={{ fontWeight: 700, fontSize: 15, color: "#0F172A", marginBottom: 12 }}>
            Suggested Allocation
          </div>
          {(s.allocation || []).map((a, idx) => (
            <div key={idx} style={{
              display: "flex",
              justifyContent: "space-between",
              marginTop: 8,
              paddingBottom: 8,
              borderBottom: idx < (s.allocation || []).length - 1 ? "1px solid #F1F5F9" : "none"
            }}>
              <div style={{ color: "#0F172A", fontSize: 14 }}>{a.channel}</div>
              <div style={{ color: "#2F5CF0", fontWeight: 600, fontSize: 14 }}>{a.amount}</div>
            </div>
          ))}

          <div style={{ marginTop: 16, fontSize: 13, color: "#94A3B8" }}>
            Estimated impressions: <strong>{metrics.impressions || "—"}</strong>
          </div>
        </div>
      </div>

      <div style={{ display: "flex", gap: 10, marginTop: 20, flexWrap: "wrap" }}>
        <button
          onClick={() => openEdit(snapshot)}
          style={{
            padding: "8px 14px",
            borderRadius: 10,
            border: "1px solid #E6EDF3",
            background: "#fff",
            cursor: "pointer",
            fontSize: 14,
            fontWeight: 500,
            color: "#0F172A"
          }}
        >
          Edit Overview
        </button>
        <button
          onClick={handleSaveDraft}
          style={{
            padding: "8px 14px",
            borderRadius: 10,
            background: "#F1F5FF",
            border: "1px solid #E6EDF3",
            cursor: "pointer",
            fontSize: 14,
            fontWeight: 500,
            color: "#2F5CF0"
          }}
        >
          Save Draft
        </button>
        <button
          onClick={() => createCampaign(snapshot)}
          style={{
            marginLeft: "auto",
            padding: "8px 14px",
            borderRadius: 10,
            background: "linear-gradient(90deg,#2F5CF0,#4D7CFF)",
            color: "#fff",
            border: "none",
            cursor: "pointer",
            fontSize: 14,
            fontWeight: 600
          }}
        >
          Create Campaign
        </button>
      </div>
    </div>
  );
}
